### ISSUE TITLE
Potentially misleading documentation

### ISSUE THREAD

**Issue by GuillaumeLeclerc** [twosixlabs/armory-example#24]
According to the documentation of `armory` (https://github.com/twosixlabs/armory#example-usage), we are supposed to find a file at the following path: `examples/fgm_attack.json`. Unfortunately it does not exist. How do I run the example?

**Comment by seanpmorgan** [comment]
Thanks @GuillaumeLeclerc. Very sorry about that... You're catching us at a bit of a tough spot when we're making some breaking changes to docs/examples while we get ready for the release on Wednesday.  Wouldn't normally want to do that but we're slightly behind schedule due to a loss in productivity these past couple of weeks.

I've created a [v0.5.0 tag on the armory-example repo](https://github.com/twosixlabs/armory-example/tree/v0.5.0) and updated the [documentation on the central README](https://github.com/twosixlabs/armory#example-usage). It's worth noting that the 0.6.0 release has a lot of changes w.r.t how scenarios work and it may be more useful to wait a day here until we have published all documentation, and 0.6.0 release + docker images.
